### ISSUE TITLE
gtp.py need a Komi function to work with sabaki

### ISSUE THREAD

**Issue by guohl** [Narsil/alphagozero#10]

**Comment by Narsil** [comment]
Which version of sabaki are you running ? I'm running 0.31.5 and it's working fine.

Otherwise, what command is it ?

**Comment by guohl** [comment]
0.32.2

**Comment by Narsil** [comment]
Ok, can you give me the sabaki gtp logs ? You can activate the logs in the engines Menu.

t

**Comment by Narsil** [comment]
It's now in master.
