### ISSUE TITLE
Easy way to import existing sgf files?

### ISSUE THREAD

**Issue by FFLaguna** [Narsil/alphagozero#14]
Is there an easy way to train the network on a large set of professional-level sgf files? I have a database of several tens of thousands of games I'd like to use to set initial weights. But I'm not sure how to put this into the format AGZ needs.

Thanks!

**Comment by Narsil** [comment]
This version uses it's own specific format.

I haven't written the code for it, but you can use the sfgmill to look into your files, then you can replay the match content:

board, player = game_init()
game_data = ...
for move in game:
   x, y = move
   make_play(x, y board)
   game_data.append ....

you can look into self_play.py in the play_game function to look what should be in the game_data.
Policy probably could be the next move played by the pro player (maybe softened, like 0.9 for pro player move and 1/n for the rest of available moves). Value is 1 if current player one, -1 if he lost.

Does that help you ?

**Comment by Narsil** [comment]
Recent version uses SGF files to store data, no way to do supervised learning yet though.
