### ISSUE TITLE
self-play: 155 parameters not match with the called function

### ISSUE THREAD

**Issue by guohl** [Narsil/alphagozero#9]

**Comment by Narsil** [comment]
Which version are you running ? This should be fixed in master.

**Comment by guohl** [comment]
A___line: 155(self_play.py):  game_data = play_game(model, model, mcts_simulations, conf['STOP_EXPLORATION'], self_play=True, resign_model1=resign, resign_model2=resign)
B___line: 32(self_play.py): def play_game(model1, model2, mcts_simulations, stop_exploration, self_play=False, num_moves=None, resign_model1=None, resign_model2=None)

**Comment by guohl** [comment]
I changed A to "game_data = play_game(model, model, mcts_simulations, conf['STOP_EXPLORATION'], self_play=True,  None, resign_model1=resign, resign_model2=resign) and the result seems correct!

**Comment by Narsil** [comment]
You should not have non named arguments (None is non named argument, after self_play=True, which is a named argument). Which version of python are you runninng ? Also num_moves should be None by default

**Comment by guohl** [comment]
the latest master

**Comment by guohl** [comment]
"game_data = play_game(model, model, mcts_simulations, conf['STOP_EXPLORATION'], True, None, resign_model1=resign, resign_model2=resign"

as above

**Comment by Narsil** [comment]
Which version of python are you running ?

**Comment by guohl** [comment]
python 3.5

**Comment by guohl** [comment]
it works fine only produces to much moves! 
if add self fill eyes check to mask in play.py(line:12) it might be much better

**Comment by guohl** [comment]
![screenshot from 2018-01-06 17-04-18](https://user-images.githubusercontent.com/3301439/34638317-10c3aba4-f304-11e7-9ebd-9640480b8f83.png)

**Comment by Narsil** [comment]
Ok, I'm closing this, for the fill eyes use #12 plz.

**Comment by guohl** [comment]
a few hours, it seems reasonable!

**Comment by guohl** [comment]
ok, thank you

**Comment by Narsil** [comment]
Don't be so sure, I've been running it on 9x9 for quite a while, it's still easily beatable. Looking at leela it looks like it needs quite a few games before making decent progress.
